[dates]
Fall = [
    "*Aug 19 - Aug 25*",
    "*Aug 26 - Sep 1*",
    "*Sep 2 - Sep 8*",
    "*Sep 9 - Sep 15*",
    "*Sep 16 - Sep 22*",
    "*Sep 23 - Sep 29*",
    "*Sep 30 - Oct 6*",
    "*Oct 7 - Oct 13*",
    "*Oct 14 - Oct 20*",
    "*Oct 21 - Oct 27*",
    "*Oct 28 - Nov 3*",
    "*Nov 4 - Nov 10*",
    "*Nov 11 - Nov 17*",
    "*Nov 18 - Nov 24*",
    "*Dec 2 - Dec 8*",
    "*Dec 9 - Dec 15*",
]

Spring = [
    "*Jan 13 - Jan 19*",
    "*Jan 20 - Jan 26*",
    "*Jan 27 - Feb 2*",
    "*Feb 3 - Feb 9*",
    "*Feb 10 - Feb 16*",
    "*Feb 17 - Feb 23*",
    "*Feb 24 - Mar 2*",
    "*Mar 3 - Mar 9*",
    "*Mar 10 - Mar 16*",
    "*Mar 24 - Mar 30*",
    "*Mar 31 - Apr 6*",
    "*Apr 7 - Apr 13*",
    "*Apr 14 - Apr 20*",
    "*Apr 21 - Apr 27*",
    "*Apr 28 - May 4*",
    "*May 5 - May 11*",
]

[ranges.Fall]
16 = "1-16"
7A = "1-7"
7B = "9-16"
8A = "1-8"
8B = "9-16"
14 = "1-14"

[ranges.Spring]
16 = "1-16"
7A = "1-7"
7B = "9-16"
8A = "1-8"
8B = "9-16"
14 = "1-14"
