[[tasks]]
name = "Begin Course Copy"
path = ""
help = "Click the --> button to start the copy"

[[tasks]]
name = "Check for Content"
path = "modules"
help = "If there is any content, don't do the copy"

[[tasks]]
name = "Delete Discussions"
path = "discussion_topics"
help = "Delete 'Student Introductions' and 'Questions and Answers'"

[[tasks]]
name = "Delete Pages"
path = "pages"
help = "Delete all pages except University Information"

[[tasks]]
name = "Verify Settings"
path = "settings"
help = "'Restrict students from viewing course before term start date' should be enabled and 'Participation' should be 'Course'"

[[tasks]]
name = "Copy Content"
path = "content_migrations"
help = "Double check the email to make sure you copy the right course"

[[tasks]]
name = "Fix Menu Order"
path = "settings#tab-navigation"
help = """Move the items in the navigation menu to this order:

Home
Announcements
Syllabus
Modules
Grades
Submit Grades
People
SE Email
Henry G. Bennett Library
Tech Support
Tutor.com
InSpace
YuJa
Panorama
Lockdown Browser
Item Banks
Credentials
Follett Discover
"""

[[tasks]]
name = "Delete Old Library"
path = "settings/configurations#tab-tools"
help = "Delete the Henry G Bennett Library item *without* new_tab=1 if it exists"

[[tasks]]
name = "Move Content"
path = "modules"
help = "Click the Auto-Move button, then the arrow in the bottom left"

[[tasks]]
name = "Delete Empty Modules"
path = "modules"
help = "Click the Remove Empty button, then the arrow in the bottom left"

[[tasks]]
name = "Add Date Headers"
path = "modules"
help = "Click the Add Dates button, wait for them to publish, then drag them to the top of their respective modules"

[[tasks]]
name = "Delete Old GOLD"
path = "modules"
help = "Delete the GOLD Orientation and the University Information which are NOT at the bottom of the START HERE module"

[[tasks]]
name = "Fix Homepage"
path = "wiki"
help = "Use https://k.ngn.tf/8775a to fix broken images; manually fix broken module links"

[[tasks]]
name = "Check Syllabus"
path = "assignments/syllabus"
help = "Check for Blackboard references, as well as getting the grade total / weights"

[[tasks]]
name = "Check Gradebook"
path = "gradebook"
help = "Make sure it matches the syllabus"

[[tasks]]
name = "Run Link Validator"
path = "link_validator"
help = "If any real links are broken, inform the professor"

[[tasks]]
name = "Check Google Sheet"
path = ""
help = "Ensure that all the steps on the Google Sheet have been followed. If something there isn't covered in the automation, lmk."

[[tasks]]
name = "Done"
path = ""
help = "Excellent work, 47. The money has been wired to your account"
